apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-operator
  labels:
    app: go-hello-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-hello-operator
  template:
    metadata:
      labels:
        app: go-hello-operator
    spec:
      containers:
      - name: go-hello-operator
        image: chouleang/go-hello-operator:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
